### ISSUE TITLE
Windows x64 ffmpeg path incorrect in verify.js

### ISSUE THREAD

**Issue by thedave42** [PotatoParser/ffmpeg-cli#1]
The current zeranoe win64 build was extracted to a different path than the one specified in verify.js, so running the library resulted in it repeatedly trying to download ffmpeg. 

This change to verify.js fixed the issue:

```
x64: {
	url: "https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.zip",
	path: __dirname + "/ffmpeg/ffmpeg-latest-win64-static/bin/ffmpeg.exe"
}
```

Windows 10 running node 10.16.0

**Comment by PotatoParser** [comment]
It looks like as if an [antivirus prevents](https://stackoverflow.com/a/50297753/11081477) the renaming of folders immediately after creation. [Fixed](https://github.com/PotatoParser/ffmpeg-cli/blob/8144ddeddf6e4a1b3c265e19d2bddec77ae6e065/lib/download.js#L50-L58) with the help of an atomic delay.
