### ISSUE TITLE
Zeranoe Download Not Available Any More

### ISSUE THREAD

**Issue by piers-walter-ibm** [PotatoParser/ffmpeg-cli#10]
The downloads for OSX are no longer available as mentioned [here](https://www.reddit.com/r/ffmpeg/comments/ikht2k/ffmpegzeranoecom_will_close_on_sep_18_2020/), I believe this will also affect the windows builds as well but don't have a windows machine to test new build downloads on sadly. 
I've located the 4.2.2 version of ffmpeg that was being used, this is where the official ffmpeg site points to now: [OSX Link](https://evermeet.cx/ffmpeg/ffmpeg-4.2.2.zip)

I've made a fork of this repo to change the download link however I get errors whenever I try to run `npm test` not sure whether this occurred on OSX before I changed the download link. My personal fork here with the issues.
There's a file called `ffmpeg-4.2.2.zip` which gets created and unzipped in the correct directory so not sure where the problem is? Hopefully this helps though

```shell
[ffmpeg-cli] Renaming files
(node:63445) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, rename '/Users/pierswalter/Documents/GitHub/ffmpeg-cli/ffmpeg/ffmpeg-4.2.2' -> '/Users/pierswalter/Documents/GitHub/ffmpeg-cli/ffmpeg/darwinx64'
    at Object.renameSync (fs.js:756:3)
    at getPackage (/Users/pierswalter/Documents/GitHub/ffmpeg-cli/lib/download.js:66:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)```

**Comment by PotatoParser** [comment]
Thanks for this! It looks like there were actually some other pieces of code that had to be fixed in order to implement the extraction of the zip correctly (The OSX zip extracts to just the FFmpeg executable instead of a folder containing the executable).
