### ISSUE TITLE
gyan.dev changed file compression extension from .zip to .7z

### ISSUE THREAD

**Issue by eightytwobees** [PotatoParser/ffmpeg-cli#13]
the URL in v2.7.0 looks for a .zip file, which no longer exists, so the site sends a 404 error that somehow gets past the code
`res.on('error', () => resolve(false));`
at line 70 in download.js (not sure if it's just sending it weird or), which creates a progress bar with a total of NaN, which crashes the tick method on the next line.

**Comment by PotatoParser** [comment]
Thanks for the catch! It looks like gyan.dev did change its links https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.zip -> https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip
