### ISSUE TITLE
request package is deprecated

### ISSUE THREAD

**Issue by leandro-manifesto** [PotatoParser/ffmpeg-cli#5]
So... the request package was deprecated. Check out request/request#3142.

AFAIK it is only used to download the ffmpeg binary and could be replaced by any other HTTP request package.

**Comment by PotatoParser** [comment]
Fixed with [![2.5.1](https://img.shields.io/badge/FFmpeg--cli-2.5.1-orange?style=flat-square)](https://github.com/PotatoParser/ffmpeg-cli/releases/tag/v2.5.1)
